# Generated by Django 5.0.6 on 2024-07-10 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_address_customer_customer_addresses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Promotions',
            new_name='Promotion',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
