# Generated by Django 5.0.6 on 2024-07-17 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_customerdetails_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerdetails',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
