# Generated by Django 5.1.1 on 2024-09-25 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_orderitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='featured_product',
        ),
        migrations.AddField(
            model_name='collection',
            name='featured_product',
            field=models.ManyToManyField(related_name='+', to='store.product'),
        ),
    ]
