version: '4.33.1'

services:
  web:
    image: your_django_image
    networks:
      - mynetwork
    environment:
      - EMAIL_HOST=smtp4dev
      - EMAIL_PORT=25
      - EMAIL_USE_TLS=False
      - EMAIL_USE_SSL=False

  smtp4dev:
    image: rnwood/smtp4dev
    networks:
      - mynetwork
    ports:
      - "25:25"
      - "8080:8080"

networks:
  mynetwork:
